language: node_js
node_js: 
  - "10.14.2"
cache:
  directories:
    - node_modules
install: 
  - npm i
  - npm i -g firebase-tools
script:
  - npm run build
# after_success:
#   - firebase deploy --token $FIREBASE_TOKEN